### ISSUE TITLE
Compatible Reflex and Reflex-Dom commits?

### ISSUE THREAD

**Issue by SamProtas** [matchwood/ghcjs-stack-dist#6]
Any chance you could provide the commits for reflex and reflex dom that you've successfully used with this compiler?

`stack setup` is still running for me so I haven't tried anything yet, but I figured if you had the information available it might save me some time.

I'd greatly appreciate any help!

**Comment by matchwood** [comment]
Sure. I've been using fairly old commits because I got them working and haven't really needed to upgrade since. Here they are
```
- location:
    git: git@github.com:reflex-frp/reflex.git
    commit: 0f5b87d14ef4cf048d41657638b5976524c41fa6
  extra-dep: true
- location:
    git: git@github.com:reflex-frp/reflex-dom.git
    commit: ff9351a1859a07f8f3892d6381e9d5d0cd500d5d
  extra-dep: true
- location:
    git: git@github.com:reflex-frp/reflex-dom-contrib.git
    commit: df4138406a5489acd72cf6c9e88988f13da02b31
  extra-dep: true

```
