### ISSUE TITLE
Cannot read property 'Signal' of undefined

### ISSUE THREAD

**Issue by mpdairy** [matchwood/ghcjs-stack-dist#7]
I can almost get your dist to work. It compiled about 90 packages but on the last one, my actual program, I get this error:

```
--  While building package dash-client-0.1.0.0 using:
      /home/teddy/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9008011_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs build lib:dash-client exe:dash-client-exe --ghcjs-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/teddy/haskell/superpowerscorp/dash/client/.stack-work/logs/dash-client-0.1.0.0.log

    Preprocessing library dash-client-0.1.0.0...
    [ 4 of 16] Compiling Db.Reaper.Types.TeamOauth ( ../common/Db/Reaper/Types/TeamOauth.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs/build/Db/Reaper/Types/TeamOauth.js_o )
    runNodeInteractive
    Linking Template Haskell (Servant.GHCJS.ConcurRouter,Taut.Types.OauthToken,Taut.Types.TeamName,ThRunner1)
    
    /tmp/ghc24383_0/ghc_36.jspp:1627:28: error:
         warning: trigraph ??/ ignored, use -trigraphs to enable [-Wtrigraphs]
             compliantExecNpcg = /()??/.exec("")[1] === undef,
                                     
    uncaught exception in Haskell main thread: TypeError: Cannot read property 'Signal' of undefined
    TypeError: Cannot read property 'Signal' of undefined
        at eval (eval at h$loadCodeStr (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10), <anonymous>:3945:27)
        at factory (eval at h$loadCodeStr (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10), <anonymous>:4287:4)
        at eval (eval at h$loadCodeStr (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10), <anonymous>:4302:26)
        at eval (eval at h$loadCodeStr (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10), <anonymous>:4304:4)
        at Object.h$loadCodeStr [as loadCodeStr] (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10)
        at Object.h$loadCode [as loadCode] (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:158:10)
        at h$$ghcjszmthzm0zi1zi0zi0zmLSgsi1E1q2eBlnv5rjMr6rZCGHCJSziPrimziTHziEval_fp (eval at h$loadCodeStr (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10), <anonymous>:73129:16)
        at h$runThreadSlice (eval at h$loadCodeStr (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10), <anonymous>:8249:11)
        at h$runThreadSliceCatch (eval at h$loadCodeStr (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10), <anonymous>:8204:12)
        at h$mainLoop (eval at h$loadCodeStr (/home/teddy/.ghcjs/x86_64-linux-0.2.1.9008011-8.0.2/ghcjs/thrunner.js:150:10), <anonymous>:8199:9)
    Data.Binary.Get.runGet at position 0: not enough bytes
    CallStack (from HasCallStack):
      error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
```

Do you by chance have any idea what this might be about?

Here're the important parts of my stack.yaml:

```
resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

packages:
- .

- location:
    git: https://github.com/NCrashed/ghcjs-base
    commit: 89c2d2fd9683fe31efac585c58d1cd909a65ba88
  extra-dep: true

extra-deps:
- ghcjs-dom-0.9.2.0
- ghcjs-dom-jsffi-0.9.2.0
- aeson-1.1.1.0
```
